services:
  db:
    image: postgres:16
    container_name: insurance_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-insurance_copilot}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: insurance_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  #backend:
  #  build: 
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  container_name: insurance_backend
  #  depends_on:
  #    - db
  #  environment:
  #    POSTGRES_CONNECTION_URI: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-insurance_copilot}
  #    OPENAI_API_KEY: ${OPENAI_API_KEY}
  #  ports:
  #    - "8000:8000"

  #frontend:
  #  build:
  #    context: ./frontend/insurance-copilot
  #    dockerfile: Dockerfile
  #  container_name: insurance_frontend
  #  depends_on:
  #    - backend
  #  ports:
  #    - "80:80"

volumes:
  db_data:
  qdrant_data:
